### PR TITLE
UPC Changes

### PR DESCRIPTION
**Pull request by njriasan**
Here are my changes to fix the formatting. Let me know if I missed anything or if anything needs changing.

### CODE REVIEW

**Comment by shankari** [comment]
@njriasan for the files that you moved, did you make sure to use `git move` to retain prior history? e.g. `emission/analysis/*`? Otherwise, it makes it a bit complicated to figure out the reason why the code looks like it does.

**Comment by njriasan** [comment]
Unfortunately I didn't. This is definitely a mistake on my part. Maybe I can explain the code structure a bit to make this less complicated. This will also look different than what was previously here in many locations. Basically there are 5 primary components: `services` (which produce the docker images that will be run), `service_router` (which contains the code which spawns the containers for each user), `shared_apis` (which are code that will be used by most services and client/aggregator code), `client_scripts` (which are meant to serve as example client code), and `aggregator_scripts`, (which are meant to serve as example aggregators).

For services, I originally had all files clumped together, originally in the `emission` direction. This featured a bunch of code from other sections and some unused/out of date code, so I decided not to copy the existing code over to the new locations. Instead I opted to pull the latest version of the server for each service and then updated `emission/core/get_database.py` (to change the database calls to use the a user's remote DB), `emission/net/api/cfc_webapp.py` (to modify which actions could be requested), `emission/analysis/classification/inference/mode/seed/section_features.py` (To make the backup use the user's remote DB and prevent a static creation of a database before a user's remote DB is known), and `emission/analysis/classification/inference/mode/seed/pipeline.py` (To make the backup use the user's remote DB).

The service router roughly corresponds to moving the existing `emission/net/api/cfc_webapp.py` to `service_router/router.py`,  `emission/net/int_service/swarm.py` to `service_router.py/swarm.py`, and `emission/net/int_service/swarm_controller.py`to  `service_router.py/launcher.py`. It also refines the implementation and adds kubernetes support in `service_router.py/launcher.py`.

The shared APIs are branch new to the code structure. The files consist of a partial implementation of the pymongo 3.5 interface to allow e-mission to connect to the user's remote DB without needing to modify code other than the database creation and it groups service router api requests into a single file. I also moved Jack's queries here in case they are reused, but since I moved them out of a separate service they no longer necessarily store the result. I also removed the `RC` query because from what i could tell Jack's didn't actually implement a noisy result and only provided a test for verify if the result would fall within the specified range (without specifying what it would be and more importantly what to do if it falls outside the provided range).
 
Client scripts modify the existing code in debug scripts to upload and download data from the user's remote database using the fake pymongo interface instead of requests to `cfc_webapp.py`. In addition it also includes examples of using each provided service.

Aggregator scripts correspond to requests to the client scripts and then implement the aggregator component of Jack's script. Once again the actual query functionality is moved into `shared_apis`.

Let me know if anything else needs clarification. My apologies again for my carelessness.

**Comment by njriasan** [comment]
Oops. Didn't mean to close this.

**Comment by shankari** [comment]
well, too late. I guess people can look at the original repo to figure out the history behind the changes. I think I might just merge this right now and deal with the history stuff later.

@jf87 what is the current state of the TU Munich students? Are they ready to start using this code?

**Comment by jf87** [comment]
@shankari I pointed them to this pull request. They are still implementing the blockchain part, but they should be ready soon ;-)

**Pull request merged**
